### ISSUE TITLE
text input is not working after you open and close the screen again

### ISSUE THREAD

**Issue by Succubussix** [breadbyte/fabric-example-imgui#2]

**Comment by Succubussix** [comment]
yeah the demo console when open it .. leave it open and close the screen and open the screen again .. u cant type

**Comment by breadbyte** [comment]
Hey, sorry for the extremely late reply! I'm having a bit of issue getting github notifications, but it's hopefully fixed now. 
I'm also following the issues https://github.com/kotlin-graphics/imgui/issues/99 and https://github.com/kotlin-graphics/imgui/issues/150 from the imgui package.

This might be an issue from my side. I've commited a fix for this c511343
